### ISSUE TITLE
hazelnut logo could use a face

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/graphics#1]
maybe some eyes peekin out from under the moppy doo

**Comment by modgethanc** [comment]
![hazelnuteyes](https://cloud.githubusercontent.com/assets/5298005/15262049/fa194fdc-192d-11e6-9449-cf94c1f2c1ce.jpg)

**Comment by cyrus-** [comment]
bahah yes.

though lil hazelnut looks sad. maybe looking off to the side?

**Comment by modgethanc** [comment]
![screen shot 2016-05-13 at 5 22 44 pm](https://cloud.githubusercontent.com/assets/5298005/15262284/54d0f94c-192f-11e6-8d91-ac95edd212e0.png)

I mean, the emo hair flop doesn't really help.

**Comment by modgethanc** [comment]
![screen shot 2016-05-13 at 5 24 55 pm](https://cloud.githubusercontent.com/assets/5298005/15262324/a1d790e8-192f-11e6-930e-e23cd47b55b8.png)

**Comment by cyrus-** [comment]
yes I vote for the half moon eyes one! the mouth is weird. no mouth.

**Comment by MichaelHilton** [comment]
I am kinda partial to the no eyes. I guess i'm just not emo enough :-)

**Comment by modgethanc** [comment]
![](https://s-media-cache-ak0.pinimg.com/736x/85/33/42/853342f6c05b1ca1d7c1166e9c7bb487.jpg)

Some Russian folk tale visual inspiration :grinning:

**Comment by MichaelHilton** [comment]
Those are awesome! I love the blue guy in the bottom left!!

**Comment by modgethanc** [comment]
This is getting weird.....

![screen shot 2016-05-13 at 5 54 55 pm](https://cloud.githubusercontent.com/assets/5298005/15262958/d51ca91c-1933-11e6-806d-ff6f4f66e876.png)

**Comment by MichaelHilton** [comment]
I don't really want people to think they have to listen to My Chemical Romance to use hazelnut

**Comment by cyrus-** [comment]
o_O

**Comment by ivoysey** [comment]
But think of how lucrative the hdb clothing line would be!

---Ian

**Comment by modgethanc** [comment]
Hey, I'm just trying to provide a range of potential solutions to the issue that Cyrus brought up.

![screen shot 2016-05-13 at 6 13 57 pm](https://cloud.githubusercontent.com/assets/5298005/15263267/8d0b97c0-1936-11e6-9d99-9ffe6df2ca39.png)

**Comment by cyrus-** [comment]
is that me should I dye my hair green for the talk and paint lines on my face?

**Comment by MichaelHilton** [comment]
Yes! nothing says commitment like dying your hair and painting your face.

**Comment by MichaelHilton** [comment]
We will know we are truly successful when there is a Hazelnut snapchat filter

**Comment by cyrus-** [comment]
hey @modgethanc could we get a vector version of the first image in this thread with the eyes looking left? we wanna put it in the paper (tonight)

**Comment by matthewhammer** [comment]
Ideally, the eyes would be looking leftward/downward, between 7 and 8 o'clock.

Specifically, we want to replace the head of the "user" in this picture, who should be looking at the latest "view", which is in that direction in this picture: 
![screen shot 2016-07-06 at 12 00 49 pm](https://cloud.githubusercontent.com/assets/1183963/16628998/5068ce68-4371-11e6-8f87-da1a32e8cb57.png)

**Comment by ivoysey** [comment]
do we want to replace the head of the stick figure? or have just Hazel labeled "user" for the whole thing? a bobble-head hazel stick figure could look kinda creepy.

**Comment by cyrus-** [comment]
just having Hazel labeled user should be good I think

**Comment by ivoysey** [comment]
Yeah, I agree. I think the label can come from Matt's diagram too but I
don't know for sure.

---Ian

**Comment by matthewhammer** [comment]
Oh, I thought we were doing bobble-head hazel stick figure. Oh, well.

**Comment by matthewhammer** [comment]
Right, I'll label Hazel as the "User" when I import this drawing into the figure above.

**Comment by modgethanc** [comment]
How's this?

![screen shot 2016-07-06 at 4 04 25 pm](https://cloud.githubusercontent.com/assets/5298005/16632712/6ad10118-4393-11e6-8df7-19dc0f899f56.png)

Dropping it onto your diagram for alignment (the box won't be around it, that's just from grabbing a preview of the rendering):

![screen shot 2016-07-06 at 4 07 00 pm](https://cloud.githubusercontent.com/assets/5298005/16632771/be519794-4393-11e6-823f-92fe0f3183f9.png)

(SVG getting pushed shortly)

**Comment by cyrus-** [comment]
Yup that's great!

**Comment by ivoysey** [comment]
I like it!

Would these colors grey-scale well? People print out papers and it
shouldn't look crappy.

---Ian

**Comment by modgethanc** [comment]
There's a greyscale version, which is tone-adjusted to read slightly better, but I just ran a straight desaturation on the colored version and it's still legible.

**Comment by ivoysey** [comment]
yeah, it's a question of what a B&W printer would do if you sent it the
colorized version more than one of making two different PDFs

---Ian

**Comment by matthewhammer** [comment]
@modgethanc Could you check in the `.ai` file for the face that you created?  (The color version).  I thought that I could import `.svg` files into omnigraffle, but it looks like it'll be easier with the `.ai` format.

**Comment by modgethanc** [comment]
I just pushed .ai and .pdf versions!

**Comment by matthewhammer** [comment]
![screen shot 2016-07-06 at 5 37 06 pm](https://cloud.githubusercontent.com/assets/1183963/16637938/582f8f22-43a0-11e6-86f0-bad3af0ef06f.png)

**Comment by ivoysey** [comment]
that's utterly wonderful. i approve.

---Ian

**Comment by cyrus-** [comment]
Beautiful.

**Comment by modgethanc** [comment]
This paper just got 20% cuter.
