### ISSUE TITLE
Color Teaks?

### ISSUE THREAD

**Issue by MichaelHilton** [hazelgrove/graphics#2]
I like the black and white version, but I feel that the brown is kinda "muddy" for the color version.  How would you feel about something more like this?
![hazelnut](https://cloud.githubusercontent.com/assets/1170420/15261190/c93e268a-190f-11e6-9fd2-5e5826613c61.jpg)

I don't have illustrator, so I just manually did it in Gimp, but I used the hex colors: 
# 8a4a32

and #5a443d

**Comment by modgethanc** [comment]
Weird; the original version had colors more like yours, but something got munged in the process of exporting all the different formats. Anyway, those colors look pretty sharp, so I'll try to remake the files to match that.

**Comment by MichaelHilton** [comment]
👍

**Comment by modgethanc** [comment]
It took me a couple passes to get the color to stick right, because I keep forgetting about color profiles!. But this should look a little snappier now!

**Comment by MichaelHilton** [comment]
looks 💯!
